name: Main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-test:
    name: 📚 Main
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache
        uses: actions/cache@v4
        with:
          path: |
            ./.eslintcache
            ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-cache
          restore-keys: |
            ${{ runner.os }}-cache

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 👀 Lint
        run: pnpm lint

      - name: 🚀 Build
        run: pnpm build

      # - name: 🧪 Test
      #   run: pnpm test
      #   env:
      #     VITE_TEST_DB_URL: ${{ secrets.VITE_TEST_DB_URL }}

      - name: 🧪 Test with coverage
        run: pnpm coverage
        env:
          VITE_TEST_DB_URL: ${{ secrets.VITE_TEST_DB_URL }}

      - name: 📝 Upload coverage
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2
